// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zylabppirmfpmibbbhfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bGFicHBpcm1mcG1pYmJiaGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NTIyMTYsImV4cCI6MjA4OTQyODIxNn0.xdCVHobG1esbmwTmCEMpIqDtrlK_pJ5lGpvJSRN66FQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});